package com.aws.lambda.data;


import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.aws.lambda.converter.ContactListConverter;
import com.fasterxml.jackson.annotation.JsonFormat;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.Date;
import java.util.List;

@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "customer")
public class Customer {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;
    @DynamoDBAttribute
    private Integer age;
    @DynamoDBAttribute
    private String name;
    @DynamoDBAttribute
    @JsonFormat(pattern = "yyyy-MM-dd", shape = JsonFormat.Shape.STRING)
    private Date dob;
    @DynamoDBAttribute
    @DynamoDBTypeConverted(converter = ContactListConverter.class)
    private List<Contact> contactList;
    @DynamoDBAttribute
    private Boolean activeFlag;
}
